package:
  name: ccj
  version: "1.0.1"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.1
  host:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]
  run:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]

about:
  home: https://github.com/HosnaJabbari/KnotAli
  summary: "Prediction of RNA pseudoknotted secondary structures using the CCJ algorithm."
  description: |
     CCJ is a computational tool for predicting RNA secondary structures with pseudoknots 
    based on Minimum Free Energy (MFE) models. It includes three implementations: Original CCJ, 
    Modified CCJ, and Sparse CCJ. Sparse CCJ, the recommended version, offers memory-efficient 
    predictions suitable for large RNA sequences.

    CCJ is implemented in C++ and requires a C++11-compatible compiler and CMake (≥3.1) for installation. 
    The software supports Linux and macOS environments and integrates the SimFold library for energy calculations.

    ### Key Features:
    - Predicts RNA secondary structures, including complex pseudoknots.
    - Offers three algorithmic variations: Original, Modified (DP09 energy model), and Sparse (optimized memory usage).
    - Supports single sequence inputs.
    - Designed for efficiency and scalability.

    Detailed installation and usage instructions can be found in the README files:
    https://github.com/HosnaJabbari/CCJ

  dev_url: https://github.com/HosnaJabbari/CCJ

extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - CCJ GCAACGAUGACAUACAUCGCUAGUCGACGC
